### ISSUE TITLE
2.1.3正常, 3.0.0报错

### ISSUE THREAD

**Issue by xjfnet** [wendux/ajax-hook#107]
D:\UserScript\xgplayer>pnpm run dev

> xgplayer@0.0.0 dev D:\UserScript\xgplayer
> vite

  VITE v4.3.9  ready in 404 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
✘ [ERROR] No matching export in "node_modules/.pnpm/ajax-hook@3.0.0/node_modules/ajax-hook/src/xhr-hook.js" for import "unHook"

    node_modules/.pnpm/ajax-hook@3.0.0/node_modules/ajax-hook/index.js:6:15:
      6 │ export { hook, unHook } from "./src/xhr-hook"
        ╵                ~~~~~~

✘ [ERROR] No matching export in "node_modules/.pnpm/ajax-hook@3.0.0/node_modules/ajax-hook/src/xhr-proxy.js" for import "unProxy"

    node_modules/.pnpm/ajax-hook@3.0.0/node_modules/ajax-hook/index.js:7:16:
      7 │ export { proxy, unProxy } from "./src/xhr-proxy"
        ╵                 ~~~~~~~

D:\UserScript\xgplayer\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1636
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 2 errors:
node_modules/.pnpm/ajax-hook@3.0.0/node_modules/ajax-hook/index.js:6:15: ERROR: No matching export in "node_modules/.pnpm/ajax-hook@3.0.0/node_modules/ajax-hook/src/xhr-hook.js" for import "unHook"
node_modules/.pnpm/ajax-hook@3.0.0/node_modules/ajax-hook/index.js:7:16: ERROR: No matching export in "node_modules/.pnpm/ajax-hook@3.0.0/node_modules/ajax-hook/src/xhr-proxy.js" for import "unProxy"
    at failureErrorWithLog (D:\UserScript\xgplayer\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1636:15)
    at D:\UserScript\xgplayer\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1048:25
    at D:\UserScript\xgplayer\node_modules\.pnpm\esbuild@0.17.19\node_modules\esbuild\lib\main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 15,
        file: 'node_modules/.pnpm/ajax-hook@3.0.0/node_modules/ajax-hook/index.js',
        length: 6,
        line: 6,
        lineText: 'export { hook, unHook } from "./src/xhr-hook"',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/.pnpm/ajax-hook@3.0.0/node_modules/ajax-hook/src/xhr-hook.js" for import "unHook"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 16,
        file: 'node_modules/.pnpm/ajax-hook@3.0.0/node_modules/ajax-hook/index.js',
        length: 7,
        line: 7,
        lineText: 'export { proxy, unProxy } from "./src/xhr-proxy"',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/.pnpm/ajax-hook@3.0.0/node_modules/ajax-hook/src/xhr-proxy.js" for import "unProxy"'
    }
  ],
  warnings: []
}

Node.js v18.12.1
 ELIFECYCLE  Command failed with exit code 1.

**Comment by xjfnet** [comment]
老项目, 只升级 ajax-hook 运行报错, 新建项目用 3.0.0 没问题

**Comment by xjfnet** [comment]
用 pnpm 添加/移除了若干个包之后, 又出现了上面的问题,

**Comment by DAHUIAAAAA** [comment]
3.0为了支持多次hook，unProxy的方式已更新，可以看下最新的文档

**Comment by xjfnet** [comment]
改了写法也是一样, 代码本身不报错, 运行  pnpm run dev 时报错

**Comment by DAHUIAAAAA** [comment]
可以更新到3.0.1这个版本再试试，fix了

**Comment by xjfnet** [comment]
更新后3.0.1后正常了
