### ISSUE TITLE
ajax-hook覆盖了XMLHttpRequest，导致XMLHttpRequest.prototype丢失

### ISSUE THREAD

**Issue by tangzhirong** [wendux/ajax-hook#111]
最近用ajax-hook实现了一个请求加密的sdk，因为ajax-hook覆盖了XMLHttpRequest，导致XMLHttpRequest.prototype丢失，这样会与其他sdk存在冲突，是不是应该重写XMLHttpRequest.prototype而不是XMLHttpRequest啊

**Comment by DAHUIAAAAA** [comment]
其他库是要获取 XMLHttpRequest.prototype 上的某个属性是吗

**Comment by onezhaoyn** [comment]
遇到同样的问题

**Comment by XinLi96** [comment]
也遇到了这个问题。。。

**Comment by DAHUIAAAAA** [comment]
试一下这个版本 ajax-hook@3.0.2
