### ISSUE TITLE
[Bug Report] Uncaught DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').

### ISSUE THREAD

**Issue by cyfung1031** [wendux/ajax-hook#117]
`Uncaught DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').`

Error found at:
```js
      var v = this.hasOwnProperty(attr + "_") ? this[attr + "_"] : this[OriginXhr][attr];
```

<img width="629" alt="Screen Shot 2023-08-16 at 18 32 35" src="https://github.com/wendux/ajax-hook/assets/44498510/ece22c46-707a-4b00-9835-a8c9d2d89540">
<img width="871" alt="Screen Shot 2023-08-16 at 18 33 17" src="https://github.com/wendux/ajax-hook/assets/44498510/f89e728b-fc20-4f90-997d-ac3a0227e4ce">

**Comment by cyfung1031** [comment]
<img width="863" alt="Screen Shot 2023-08-16 at 19 07 47" src="https://github.com/wendux/ajax-hook/assets/44498510/1531b467-7d18-4354-b56b-cc096296276c">

**Comment by cyfung1031** [comment]
* The issue is in the `handler.next(config)` inside `onRequest`
```

ah.proxy({
            onRequest: (config, handler) => {
                console.log(config)
                handler.next(config)
            },
           ...
})
```

<img width="950" alt="Screen Shot 2023-08-16 at 19 11 34" src="https://github.com/wendux/ajax-hook/assets/44498510/f5472475-19f7-4ec1-8eb3-a8ab0a92e553">

**Comment by cyfung1031** [comment]
#93

**Comment by Yooi** [comment]
well done, it fixed my issue
