### ISSUE TITLE
你好为什么我只有初始化的时候能够触发钩子，而后续的请求都没反应？

### ISSUE THREAD

**Issue by PL-FE** [wendux/ajax-hook#125]
Edge 浏览器正常
Chrome 浏览器不行

 **Edge: Spartan (44.22621.2134.0)** 【正常】
 **Chromium (116.0.1938.62)** 【只有首次，后续像是XMLHttpRequest被还原了】

**Comment by PL-FE** [comment]
axios 是0.21.4 ,比较旧了

**Comment by DAHUIAAAAA** [comment]
尝试下最新的版本呢？

**Comment by PL-FE** [comment]
感谢回复，是谷歌插件冲突了。。Ajax Modifier 也重写了ajax..
