### ISSUE TITLE
[Bug Report] Conflict with uBlock Origin

### ISSUE THREAD

**Issue by cyfung1031** [wendux/ajax-hook#127]
If uBlock Origin is enabled, YouTube will be frozen due to the conflict with ajax-hook.

## Reproduction:
1. Use Chrome (or Firefox)
2. Install uBlock Origin (v1.51.0)
3. Install Userscript Manager Tampermonkey or Violentmonkey
<img width="844" alt="Screen Shot 2023-09-02 at 19 22 08" src="https://github.com/wendux/ajax-hook/assets/44498510/aa6d6cf9-85a3-4adb-a257-b590c6eea2aa">

5. create a new userscript to let the code inject at the very first begining.
```js
// ==UserScript==
// @name        Testing 333
// @namespace   TestScripts
// @match       https://www.youtube.com/*
// @grant       none
// @version     1.0
// @author      abc
// @description Testing
// @require     https://github.com/wendux/ajax-hook/raw/master/dist/ajaxhook.js
// @run-at      document-start
// ==/UserScript==

ah.proxy({
    onRequest: (config, handler) => {
        handler.next(config);
    },
    onResponse: (response, handler) => {
        handler.resolve(response);
    }
});
```
6. open youtube.com
7. frozen

## Screenshots

Chrome:

<img width="1509" alt="Screen Shot 2023-09-02 at 19 21 36" src="https://github.com/wendux/ajax-hook/assets/44498510/5ed9ca79-c34f-49a1-a381-d93c9957e771">

Firefox:

<img width="1304" alt="Screen Shot 2023-09-02 at 19 23 47" src="https://github.com/wendux/ajax-hook/assets/44498510/aac4f81b-4f04-4b41-a4c1-d40343eb3396">

## Console Error:

Chrome:
<img width="907" alt="Screen Shot 2023-09-02 at 19 25 14" src="https://github.com/wendux/ajax-hook/assets/44498510/1ae4cc74-d008-4d24-ac6a-fbf9c27fbb03">

Firefox:
<img width="578" alt="Screen Shot 2023-09-02 at 19 24 56" src="https://github.com/wendux/ajax-hook/assets/44498510/f0336d4a-9d3c-437f-a5bb-452e000b5c33">

## Remarks 1:

Tried to downgrade to earlier version like 
 Jun 14, 2022 https://github.com/wendux/ajax-hook/commit/9efea44c8b2bc27b5ec0e8c2e3a2477bdc76dab9
https://github.com/wendux/ajax-hook/raw/9efea44c8b2bc27b5ec0e8c2e3a2477bdc76dab9/dist/ajaxhook.js

Same result.

## Remarks 2:

If PR #120 is applied, the issue might get resolved by bypassing the urls.

**Comment by DAHUIAAAAA** [comment]
bypass 的问题不着急过，先看看是什么原因导致的，是哪些原因导致的冲突，再从问题下手，onConfig 的方式虽然说可以饶过一整条链路，但是这个配置项一眼过去比较难理解是用来干什么的

**Comment by cyfung1031** [comment]
> bypass 的问题不着急过，先看看是什么原因导致的，是哪些原因导致的冲突，再从问题下手，onConfig 的方式虽然说可以饶过一整条链路，但是这个配置项一眼过去比较难理解是用来干什么的

對，那個不用緊
這個衝突可能需要把整個底層重寫

剛試寫了一下，如果是用Inherit Class 的方法寫getter的話，是可以做到相同效果又不會出現衝突。 
https://github.com/culefa/xhProxy/blob/main/dist/xhProxy.js
示範：https://greasyfork.org/en/scripts/473130-ytdls-youtube-dual-language-subtitle-modified

**Comment by DAHUIAAAAA** [comment]
看起来不错，可以试试~ 不过是什么原因呢？

**Comment by cyfung1031** [comment]
我在Chrome和Firefox試了一下
只把Lists更新或者是Purge或者是取消uBlock filters - ads也是沒用的
把uBO裡面的Built-in lists 把uBlock filters - Quick fixes 取消打勾，套用，再打勾再套用，就沒事了
之後即使把uBO的設定初始化，或是reinstall也是沒事的
