### ISSUE TITLE
在weibo首页使用会触发weibo底层代码报错

### ISSUE THREAD

**Issue by Fbozhou** [wendux/Ajax-hook#135]
大佬能否帮忙看个问题，基于ah.proxy()方法写了个过滤请求的脚本，正常使用了有3年了，最近突然 “全部关注”tab页的数据无法加载，查看控制台发现开启ah之后会少一个请求，怀疑可能是有地方导致微博底层代码报错 以至于微博的代码无法正常执行？但是其他tab页的数据都能正常返回拦截后的数据。

也尝试过去除多余的逻辑，但是发现只要开启了ah.proxy()，“全部关注”页面的数据就无法正常显示

[脚本地址](https://github.com/Fbozhou/scripts/blob/main/%E5%BE%AE%E5%8D%9A%E5%8E%BB%E5%B9%BF%E5%91%8A/weibo_adblock.user.js)

![图片](https://github.com/user-attachments/assets/b4116957-db97-4494-85a6-fa9e3384ec63)
![图片](https://github.com/user-attachments/assets/a89c3963-3602-49b9-82d7-42ec4e7c6506)
![图片](https://github.com/user-attachments/assets/964eae95-b804-4a31-81df-05014fb0cc9a)

**Comment by sfiction** [comment]
我也遇到了一样的问题，暂时用 `ah.hook({open: <func>}, unsafeWindow)` 解决了，不过我原先只用到了 `onResponse`。
可以仿照 `src/xhr-proxy.js` 里的封装改用 `ah.hook`。

**Comment by sfiction** [comment]
定位之后发现注释掉 [src/xhr-proxy.js#L196](https://github.com/wendux/ajax-hook/blob/master/src/xhr-proxy.js#L196) 这一行就没问题了。解决方案有两种：

1. 在 `ah.proxy` 的 `onResponse` 回调中加一行 `delete response.config.xhr;` 将其移除。
2. 手动编辑脚本的外部资源，注释掉这一行。

也许微博代码里遍历了 xhr 对象，所以不能出现循环引用？

**Comment by Fbozhou** [comment]
> 定位之后发现注释掉 [src/xhr-proxy.js#L196](https://github.com/wendux/ajax-hook/blob/master/src/xhr-proxy.js#L196) 这一行就没问题了。解决方案有两种：
> 
>     1. 在 `ah.proxy` 的 `onResponse` 回调中加一行 `delete response.config.xhr;` 将其移除。
> 
>     2. 手动编辑脚本的外部资源，注释掉这一行。
> 
> 
> 也许微博代码里遍历了 xhr 对象，所以不能出现循环引用？

大佬牛，用hook重写了一下ok了，感谢！
