### ISSUE TITLE
可以不走网络请求，直接返回数据吗，用来开发期间模拟接口

### ISSUE THREAD

**Issue by ipad4** [wendux/Ajax-hook#15]
不走网络请求，直接返回数据，我将send方法里return true，但不知道如何将模拟的响应数据传给xhr

**Comment by wendux** [comment]
不走网络请求可以，但要返回指定数据用这个库不是很方便，有mock需求的化可以使用fly来拦截会很方便：https://wendux.github.io/dist/#/doc/flyio/hook
