### ISSUE TITLE
  Object.defineProperty responseText在android 5.1 oppo 中无效，导致异步请求无法获取数据

### ISSUE THREAD

**Issue by shibiaoz** [wendux/Ajax-hook#26]
## 系统
手机名称：OPPO A59S
colorOs:v 3.0 
Android:5.1
## 表现
无法获取请求返回数据，

## 原因
通过Object.defineProperty设置的属性response, responseText 不生效，需要显示的
在onreadystatechange 中手动设置
在https://github.com/wendux/Ajax-hook/blob/master/src/ajaxhook.js#L48
之前添加
```
if (attr === 'onreadystatechange') {                   
    that.responseText = that.xhr.responseText;
    that.response = that.xhr.response;
}
```

**Comment by wendux** [comment]
请使用最新版重试
