### ISSUE TITLE
方法的HOOK，为什么在方法代理的时候不把返回值也返回呢

### ISSUE THREAD

**Issue by karosLi** [wendux/Ajax-hook#32]
现在：
function hookFunction(fun) {
                return function () {
                    var args = [].slice.call(arguments);
                    if (proxy[fun] && proxy[fun].call(this, args, this.xhr)) {
                        return;
                    }
                    return this.xhr[fun].apply(this.xhr, args);
                };
            }

期望：
function hookFunction(fun) {
                return function () {
                    var args = [].slice.call(arguments);
                    if (proxy[fun]) {
                        return proxy[fun].call(this, args, this.xhr);
                    }
                    return this.xhr[fun].apply(this.xhr, args);
                };
            }

**Comment by wendux** [comment]
已经修复了
