### ISSUE TITLE
支持拦截fetch吗？

### ISSUE THREAD

**Issue by lgoldfish** [wendux/ajax-hook#36]

**Comment by karosLi** [comment]
同问

**Comment by waterfly** [comment]
同问

**Comment by wendux** [comment]
不支持fetch，原因是fetch接口规范很简单，要拦截fetch也很简单，直接复写就可以，几行代码就行，徒手写出来：
``` javascript
var _f=fetch
window.fetch=function(){
   // do something
 return   _f.apply(window, arguments)
}
```

**Comment by wendux** [comment]
不支持fetch，原因是fetch接口规范很简单，要拦截fetch也很简单，直接复写就可以，几行代码就行，徒手写出来：
``` javascript
var _f=fetch
window.fetch=function(){
   // do something
 return   _f.apply(window, arguments)
}
```

**Comment by k713927** [comment]
> 不支持fetch，原因是fetch接口规范很简单，要拦截fetch也很简单，直接复写就可以，几行代码就行，徒手写出来：
> 
> ```js
> var _f=fetch
> window.fetch=function(){
>    // do something
>  return   _f.apply(window, arguments)
> }
> ```

获取fetch的返回值怎么写呢

**Comment by acbetter** [comment]
fetch 直接照这个写就行了，拦截起来不麻烦。

https://stackoverflow.com/questions/45425169/intercept-fetch-api-requests-and-responses-in-javascript
