### ISSUE TITLE
请教：拦截jsonp请求

### ISSUE THREAD

**Issue by WuHuaJi0** [wendux/Ajax-hook#4]
楼主这个东西很好用，在之前的项目中用上了：）

现在的需求是要拦截jsonp请求，楼主的这个就用不上了，想了半天没好办法，所以特来请教下，不知有什么思路吗？

**Comment by wendux** [comment]
jsonp 并不是通过ajax发起的，不能拦截。如果有这个需求，大致可以通过覆盖相关库的jsonp方法实现。

**Comment by WuHuaJi0** [comment]
嗯，多谢，我后来也琢磨出来了，先是监控页面创建script节点，然后判断是否是要拦截的请求，再重写全局的callback方法。大致是这个思路
