### ISSUE TITLE
使用之后同步请求不在同步

### ISSUE THREAD

**Issue by Gahon1995** [wendux/Ajax-hook#47]
使用proxy进行拦截以后，发现之前设置的同步请求在会同步执行了，看起来更像是异步执行，取消掉proxy能够正常执行，但是加上这个就像异步执行了。

另外设置config.withCredentials=true 好像无效， 通过设置config.xhr.withCredentials=true 才能生效，不知道是我用法不对还是有bug

**Comment by wendux** [comment]
你的用法没问题，2.0.1版本修复了，试试
