### ISSUE TITLE
Access to request FormData

### ISSUE THREAD

**Issue by ilansr** [wendux/Ajax-hook#5]
Hi
Is it possible to get read access to the request body when using POST/PUT request **with** the request url?
The xhr object does not contain this data
Closest I got to is:
```
ah.hookAjax({
    send:function(arg,xhr){
         console.log("send args = %s", arg.join()); //body, but no url
    },
    onreadystatechange:function(xhr){
        console.log("responseURL: %s", xhr.responseURL); //url, but no request body
});
  ```
Is there a way to get both request-body and request-url in same context?

Thanks!

**Comment by wendux** [comment]
you can get request url by hooking open .   get the request data by hooking send  , the request data in arguments of send .

**Comment by wendux** [comment]
the same context with the same xhr object .
