### ISSUE TITLE
美团外卖做了防Hook。

### ISSUE THREAD

**Issue by xlzhen-940218** [wendux/ajax-hook#50]
Uncaught RangeError: Maximum call stack size exceeded

代码位置：
function o(t) {
		function e(e) {
			return function() {//这里会报递归调用
				var r = this.hasOwnProperty(e + "_") ? this[e + "_"] : this.xhr[e],
					n = (t[e] || {}).getter;
				return n && n(r, this) || r
			}
		}

想知道该如何解决？

**Comment by xlzhen-940218** [comment]
1.8版本会报同样的错误，错误位置：

t.hookAjax = function(t) {
			function r(n) {
				return function() {//这里会报递归调用
					var r = this.hasOwnProperty(n + "_") ? this[n + "_"] : this.xhr[n],
						e = (t[n] || {}).getter;
					return e && e(r, this) || r
				}
			}

**Comment by ZengTianShengZ** [comment]
有复现的地方吗，如何复现

**Comment by 303182519** [comment]
升级3.0就不会
