### ISSUE TITLE
iframe的请求hook问题

### ISSUE THREAD

**Issue by tonymiao2012** [wendux/Ajax-hook#51]
请问下这个库是否支持hook到同一个页面，内嵌iframe子页面的所有xmlHttpRequest请求呢？谢谢

**Comment by xiaoganggang** [comment]
不支持，我尝试是不可以的的。

**Comment by wendux** [comment]
https://github.com/wendux/Ajax-hook#%E6%8B%A6%E6%88%AAiframe
