### ISSUE TITLE
IE 兼容性问题

### ISSUE THREAD

**Issue by TJZhou** [wendux/Ajax-hook#52]
其他浏览器没有问题，IE碰到了个奇怪的问题

“Inspector returns the error: Object doesn't support this action”

Debug后发现是xor-proxy.js 文件 triggerListenner方法最后的getEventType(xhr).dispatchEvent抛出的异常

参考这个问题 https://stackoverflow.com/questions/27176983/dispatchevent-not-working-in-ie11

修改成

    var evt;
    if(typeof(Event) === 'function') {
        evt = new Event(name);
    } else {
        evt = document.createEvent('Event');
        evt.initEvent(name, false, true);
    }
    getEventTarget(xhr).dispatchEvent(evt);

解决了这个IE兼容性问题，

要是作者有时间的话可以拿IE试一下。

**Comment by wendux** [comment]
2.0.3已修复
