### ISSUE TITLE
并不是所有的请求都能拦截到？

### ISSUE THREAD

**Issue by huanghanzhilian** [wendux/Ajax-hook#6]

**Comment by wendux** [comment]
只要是通过xmlhttprequest 发起的请求，都能拦截

**Comment by huanghanzhilian** [comment]
谢谢您，我是用的hls流媒体播放，请求的视频片源.ts后缀的get请求无法拦截。可能是hls库做了不一样的工作。谢谢。

**Comment by wll8** [comment]
> 谢谢您，我是用的hls流媒体播放，请求的视频片源.ts后缀的get请求无法拦截。可能是hls库做了不一样的工作。谢谢。

你能拦截了吗？
