### ISSUE TITLE
无法拦截到高德地图的自请求接口。无论是用proxy还是hook都不会进入对应的拦截方法。

### ISSUE THREAD

**Issue by mariree** [wendux/Ajax-hook#65]
类似于这种接口，无法拦截到
![image](https://user-images.githubusercontent.com/44171557/99778857-37973800-2b4f-11eb-946b-a5c04086e6fc.png)

**Comment by gaoyaoman** [comment]
解决了吗老哥

**Comment by mariree** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    后台做nginx代理解决的。纯前端解决不了。
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1124228227
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年7月5日 ***@***.***> 写道： 




解决了吗老哥



—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by gaoyaoman** [comment]
是的，但问题是我在前端都没有办法拦截高德地图的自调用请求，那我该怎么用nginx去代理呢？

**Comment by gaoyaoman** [comment]
我知道了，谢谢

**Comment by mariree** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    做URL匹配，高德地图的自请求只有那么几种域名开头的，ng可以拦截到，具体看下配置。ng玩的溜的话，甚至还能修改请求到的内容。后台和运维人员弄得，具体我也不会。
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1124228227
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年7月5日 ***@***.***> 写道： 




是的，但问题是我在前端都没有办法拦截高德地图的自调用请求，那我该怎么用nginx去代理呢？



—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by caoruonan** [comment]
解决了吗？

**Comment by caoruonan** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 做URL匹配，高德地图的自请求只有那么几种域名开头的，ng可以拦截到，具体看下配置。ng玩的溜的话，甚至还能修改请求到的内容。后台和运维人员弄得，具体我也不会。 1124228227 ***@***.*** 签名由 网易邮箱大师 定制 在2021年7月5日 ***@***.***> 写道： 是的，但问题是我在前端都没有办法拦截高德地图的自调用请求，那我该怎么用nginx去代理呢？ —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.



> 我知道了，谢谢

怎么解决的呀

**Comment by eating-noodles** [comment]
> > font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 做URL匹配，高德地图的自请求只有那么几种域名开头的，ng可以拦截到，具体看下配置。ng玩的溜的话，甚至还能修改请求到的内容。后台和运维人员弄得，具体我也不会。 1124228227 _**@**_.*** 签名由 网易邮箱大师 定制 在2021年7月5日 _**@**_.***> 写道： 是的，但问题是我在前端都没有办法拦截高德地图的自调用请求，那我该怎么用nginx去代理呢？ —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> > 我知道了，谢谢
> 
> 怎么解决的呀

+1 请问大佬 有解决了吗？怎么解决的
