### ISSUE TITLE
请问这个插件会跟axios冲突吗？

### ISSUE THREAD

**Issue by zhoufanglu** [wendux/Ajax-hook#69]
我使用了高德地图，ajax-hook是能拦截到高德地图的请求
axios就不能， 我安装了ajax-hook，但是axios接口就不请求了。

**Comment by jsonsnow** [comment]
目前也遇到了这个问题，最后调试是不冲突的吗

**Comment by jsonsnow** [comment]
axios的hook只在他们框架内，之间不存在冲突

**Comment by eating-noodles** [comment]
大佬，想请求下怎么做？我拦截不到高德所有接口，有的接口拦截不到。
