### ISSUE TITLE
hook 会覆盖掉 XMLHttpRequest.DONE 等状态常量，导致依赖该常量判断的网站出错

### ISSUE THREAD

**Issue by zvrh** [wendux/Ajax-hook#72]
在 XMLHttpRequest 中添加以下常量即可
``` javascript
const UNSENT = 0;
const OPENED = 1;
const HEADERS_RECEIVED = 2;
const LOADING = 3;
const DONE = 4;
```

参考：
https://xhr.spec.whatwg.org/
https://developer.mozilla.org/zh-CN/docs/Web/API/XMLHttpRequest/readyState

**Comment by madokaa** [comment]
在作者修复前，可以自己在hook后面增加下面代码即可
``` javascript
ah.proxy({ });
// proxy 或 hook 后面增加以下代码
Object.assign(XMLHttpRequest, { UNSENT: 0, OPENED: 1, HEADERS_RECEIVED: 2, LOADING: 3, DONE: 4 });
```

**Comment by laoboxie** [comment]
> 在作者修复前，可以自己在hook后面增加下面代码即可
> 
> ```js
> ah.proxy({ });
> // proxy 或 hook 后面增加以下代码
> Object.assign(XMLHttpRequest, { UNSENT: 0, OPENED: 1, HEADERS_RECEIVED: 2, LOADING: 3, DONE: 4 });
> ```

我最近也要做前端接口监控的需求，找来找去，也没找到一种优雅的、侵入性比较小的劫持XHR的方式。
我看了很多库，都发现他们的实现会丢掉对象本身的属性。
也没有人能提供一种优雅的、安全的函数劫持/代理的方式
