### ISSUE TITLE
onreadystatechange方法没有被回调，但是onload被回调了

### ISSUE THREAD

**Issue by lishichao1002** [wendux/ajax-hook#78]
使用的axios，发现axios(url).then().catch() 中 then 和catch都不会调用，debugger了一下发现axios里面用的onreadystatechange，不会被调用，手动加上onload后，发现onload会被调用

**Comment by lxdreamer** [comment]
请问这个后来怎么解决了，我也发现了这个问题

**Comment by wendux** [comment]
首先用最新版，其次axios里会优先使用xhr的onloadend回调，如果没有onloadend才会使用onreadystatechange，所以可以拦截onloadend
