### ISSUE TITLE
如何在send阶段获取url

### ISSUE THREAD

**Issue by RiJOKy** [wendux/Ajax-hook#9]
hook以后相对数据进行加密，但是加密需要根据不同的url来判断。怎么在send阶段拿到url呢？

**Comment by RiJOKy** [comment]
我想了一个在open中，加一句 xhr['open_arg'] = arg;

**Comment by wendux** [comment]
对的！可以把需要在上下文中共享的数据动态添加到xhr对象上，因为同一个上下文中xhr对象是同一个，the same context with the same xhr object .
