### ISSUE TITLE
iframe拦截缺少必要参数

### ISSUE THREAD

**Issue by tianzhijiexian** [wendux/ajax-hook#90]
原始提交地址：
https://github.com/wendux/ajax-hook/commit/3fbc6fcad728548ad1031aa60a922a1ba5e39e4f#

<img width="635" alt="image" src="https://user-images.githubusercontent.com/9552155/171108612-de66e480-9944-4054-b458-a728e77904e1.png">

新增win变量
![Uploading image.png…]()

**Comment by tianzhijiexian** [comment]
<img width="632" alt="image" src="https://user-images.githubusercontent.com/9552155/171109499-2ebc2377-e413-4375-97f9-9a51e9f70dac.png">

**Comment by wendux** [comment]
2.1.0中已修改
