### ISSUE TITLE
Uncaught SyntaxError: The requested module '/js/ajaxhook.min.js' does not provide an export named 'proxy

### ISSUE THREAD

**Issue by SeanHsueh666** [wendux/ajax-hook#92]
请问大佬这是怎么处理，第一次用es6，紧急任务啊，来不及系统学

import {proxy, unProxy} from "/js/ajaxhook.min.js";

proxy({
    //请求发起前进入
    onRequest: (config, handler) => {
        console.log(config.url)
        handler.next(config);
    },
    //请求发生错误时进入，比如超时；注意，不包括http状态码错误，如404仍然会认为请求成功
    onError: (err, handler) => {
        console.log(err.type)
        handler.next(err)
    },
    //请求成功后进入
    onResponse: (response, handler) => {
        console.log(response.response)
        handler.next(response)
    }
})

报错
Uncaught SyntaxError: The requested module '/js/ajaxhook.min.js' does not provide an export named 'proxy
大佬解决了有赞助啊双份

**Comment by DAHUIAAAAA** [comment]
ah.proxy({})，这样再试试
