### ISSUE TITLE
修改请求时的header失败

### ISSUE THREAD

**Issue by superen7527** [wendux/ajax-hook#94]
请问是在发起请求前修改吗？

修改了config.body修改成功
修改了config.headers内部参数也在config.log上看到了修改成功

提交以后，对浏览器抓包
发现只有body修改成功也在抓包记录里面
header里面的cookie和referer都修改失败，不显示

尝试修改config.xml.reHeader 直接修改config.xml 都不行 报错null

**Comment by DAHUIAAAAA** [comment]
referer 前端无法修改，cookie被设置了 httpOnly 也无法修改
